### PR TITLE
Style modal

### PR DESCRIPTION
**Pull request by styrbjorn-n**
Modal now looks and works as intended in figma

### CODE REVIEW

**Comment by styrbjorn-n** [comment]
The modal is missing styled error messages.

**Comment by sebastianandreasson** [comment]
image

The input fields for deadline and date are too small so the text for the placeholder does not fit and the date becomes two lines. I think it can fill the entire width of the container.

**Comment by sebastianandreasson** [comment]
image
When Editing a deadline the icon for save is the bookmark icon, it should be a save icon ( like the floppy disk )

**Comment by sebastianandreasson** [comment]
I would also place the FAB + modal visibility in its own component called EventModalButton or something like this and place it outside the header since it's no longer actually inside the header. It could be directly in the App.jsx

```
<ActionIcon
                    pos="absolute"
                    bottom={100}
                    right={100}
                    variant="outline"
                    onClick={() => {
                        setModalOpen(true)
                    }}
                    size={50}
                >
                    <FontAwesomeIcon icon={faPlus} />
                </ActionIcon>
                {!!modalOpen && <NewEventModal closeModal={closeModal} />}
```

**Comment by sebastianandreasson** [comment]
Other than these comments it looks good to me, fix those and it's good to merge

**Comment by sebastianandreasson** [comment]
image

It got a bit worse than before, I also tried it on a bigger screen but it still cuts off the date input to 2 lines.

**Comment by sebastianandreasson** [comment]
I would make the width of the modal a fixed PX size instead of 25% of screen, maybe on mobile it could be 90vw or something like this, but at the moment we don't really care about the mobile layout

**Comment by sebastianandreasson** [comment]
👍

**Pull request merged**
